// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./src/components/Pie/index.vue')['default']
    China: typeof import('./src/components/China/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Line: typeof import('./src/components/Line/index.vue')['default']
    Pie: typeof import('./src/components/Pie/index.vue')['default']
    'Pie copy': typeof import('./src/components/Pie copy/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
  }
}

export { }
